# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: berkeley.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62\x65rkeley.proto\x12\x08\x62\x65rkeley\"\x07\n\x05\x45mpty\"\x1c\n\x0cTimeResponse\x12\x0c\n\x04time\x18\x01 \x01(\x03\x32@\n\x08TimeSync\x12\x34\n\x07GetTime\x12\x0f.berkeley.Empty\x1a\x16.berkeley.TimeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'berkeley_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=28
  _globals['_EMPTY']._serialized_end=35
  _globals['_TIMERESPONSE']._serialized_start=37
  _globals['_TIMERESPONSE']._serialized_end=65
  _globals['_TIMESYNC']._serialized_start=67
  _globals['_TIMESYNC']._serialized_end=131
# @@protoc_insertion_point(module_scope)
